#!/usr/bin/env python3
"""Download and clean English medical wordlists from CodeSante/medical-wordlist."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
import unicodedata
import urllib.error
import urllib.request
from pathlib import Path

from app.services.ocr.medical_terms import (
    bundled_research_core_wordlist_path,
    parse_wordlist_file,
    normalize_wordlist_term,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_OUTPUT_DIR = _REPO_ROOT / "data" / "models" / "medical-wordlist"
_BASE_URL = "https://raw.githubusercontent.com/CodeSante/medical-wordlist/main/en/{filename}"

# Curated OCR-friendly subsets from https://github.com/CodeSante/medical-wordlist
SOURCE_FILES: tuple[tuple[str, str], ...] = (
    ("medication-wordlist.en.txt", "medication.txt"),
    ("medical-speciality-wordlist.en.txt", "specialities.txt"),
    ("medical-examination-wordlist.en.txt", "examinations.txt"),
    ("diseases-wordlist.en.txt", "diseases.txt"),
    ("degenerative-disease-wordlist.en.txt", "degenerative-diseases.txt"),
    ("health-problem-wordlist.en.txt", "health-problems.txt"),
    ("most-popular-terms-chatgpt4.en.txt", "core-terms.txt"),
)

_TOKEN_SPLIT_RE = re.compile(r"[\s/(),]+")


def _download_source(filename: str, *, timeout_seconds: int = 60) -> str:
    url = _BASE_URL.format(filename=filename)
    request = urllib.request.Request(url, headers={"User-Agent": "ResearchDock-wordlist-builder/1.0"})
    with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
        return response.read().decode("utf-8")


def extract_ocr_terms(raw_line: str) -> set[str]:
    line = str(raw_line or "").strip()
    if not line or line.startswith("#"):
        return set()

    folded = unicodedata.normalize("NFKD", line).encode("ascii", "ignore").decode("ascii")
    terms: set[str] = set()
    for chunk in _TOKEN_SPLIT_RE.split(folded):
        token = chunk.strip(" .;:-")
        normalized = normalize_wordlist_term(token)
        if normalized:
            terms.add(normalized)
    return terms


def clean_source_text(text: str) -> list[str]:
    terms: set[str] = set()
    for raw_line in text.splitlines():
        terms.update(extract_ocr_terms(raw_line))
    return sorted(terms)


def write_wordlist(path: Path, terms: list[str], *, source_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Generated by backend/scripts/build_medical_wordlist.py\n"
        f"# Source: CodeSante/medical-wordlist ({source_name})\n"
        f"# Terms: {len(terms)}\n"
    )
    path.write_text(header + "\n".join(terms) + ("\n" if terms else ""), encoding="utf-8")


def copy_bundled_research_core(output_dir: Path) -> int:
    bundled_path = bundled_research_core_wordlist_path()
    if not bundled_path.exists():
        raise SystemExit(f"Bundled research-core wordlist missing: {bundled_path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "research-core.txt"
    shutil.copy2(bundled_path, output_path)
    return len(parse_wordlist_file(output_path))


def build_wordlists(output_dir: Path, *, skip_download: bool = False) -> dict[str, int]:
    counts: dict[str, int] = {}

    research_path = output_dir / "research-core.txt"
    if skip_download and research_path.exists():
        counts[research_path.name] = len(parse_wordlist_file(research_path))
    else:
        counts[research_path.name] = copy_bundled_research_core(output_dir)

    for source_name, output_name in SOURCE_FILES:
        output_path = output_dir / output_name
        if skip_download and output_path.exists():
            counts[output_name] = sum(
                1
                for line in output_path.read_text(encoding="utf-8").splitlines()
                if line.strip() and not line.startswith("#")
            )
            continue

        try:
            source_text = _download_source(source_name)
        except urllib.error.URLError as exc:
            raise SystemExit(f"Failed to download {source_name}: {exc}") from exc

        cleaned_terms = clean_source_text(source_text)
        write_wordlist(output_path, cleaned_terms, source_name=source_name)
        counts[output_name] = len(cleaned_terms)

    return counts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Download and clean CodeSante medical wordlists for OCR postprocess."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=_DEFAULT_OUTPUT_DIR,
        help=f"Output directory for cleaned wordlists (default: {_DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="Skip downloading when output files already exist.",
    )
    args = parser.parse_args(argv)

    output_dir = args.output_dir.resolve()
    counts = build_wordlists(output_dir, skip_download=args.skip_download)

    print(f"Wrote {len(counts)} wordlist files to {output_dir}")
    for name, count in sorted(counts.items()):
        print(f"  - {name}: {count} terms")
    print(f"Total unique files: {len(counts)} terms across files (may overlap between files)")
    print(f"Bundled defaults source: {bundled_research_core_wordlist_path()}")
    print(f"Set OCR_MEDICAL_WORDLIST_PATH={output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
